# Usar una imagen base de Nginx
FROM nginx:alpine

# Copiar el resultado de la construcción desde la imagen de Node.js
COPY --from=blp-static-page_node /app/dist /usr/share/nginx/html

# Copiar la configuración de Nginx
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto en el que correrá Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
